rrbot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  j1_position_controller:
    type: position_controllers/JointPositionController
    joint: joint1
    pid: {p: 1000.0, i: 0.01, d: 10.0}
  j2_position_controller:
    type: position_controllers/JointPositionController
    joint: joint2
    pid: {p: 1000.0, i: 0.01, d: 10.0}
  j3_position_controller:
    type: position_controllers/JointPositionController
    joint: joint3
    pid: {p: 1000.0, i: 0.01, d: 10.0}
  j4_position_controller:
    type: position_controllers/JointPositionController
    joint: joint4
    pid: {p: 1000.0, i: 0.01, d: 10.0}
  j5_position_controller:
    type: position_controllers/JointPositionController
    joint: joint5
    pid: {p: 1000.0, i: 0.01, d: 10.0}
  j6_position_controller:
    type: position_controllers/JointPositionController
    joint: joint6
    pid: {p: 1000.0, i: 0.01, d: 10.0}

  /gazebo_ros_control:
    pid_gains:
      joint1:
        p: 1000.0
        i: 0.01
        d: 10.0
      joint2:
        p: 1000.0
        i: 0.01
        d: 10.0
      joint3:
        p: 1000.0
        i: 0.01
        d: 10.0
      joint4:
        p: 1000.0
        i: 0.01
        d: 10.0
      joint5:
        p: 1000.0
        i: 0.01
        d: 10.0
      joint6:
        p: 1000.0
        i: 0.01
        d: 10.0
